// English UI strings for dnd55e-sheets — the source of truth.
//
// Flat key → string catalog, mirroring the host's /i18n/en.json shape. English
// is always present and is the universal fallback; other locales layer on top
// (drop a strings/<locale>.js and registerCatalog it in entry.js — no other
// change). {placeholders} are interpolated by i18n.t(). Keep this file English
// only; translations never live here.

export default {
  // ── Tabs ─────────────────────────────────────────────────────────
  'tab.overview':     'Overview',
  'tab.sheet':        'Sheet',
  'tab.spellbook':    'Spellbook',
  'tab.backpack':     'Backpack',
  'tab.builder':      'Builder',

  // ── Section headers ──────────────────────────────────────────────
  'sheet.title':      'Character Sheet',
  'sheet.identity':   'Identity',
  'sheet.abilities':  'Ability Scores',
  'sheet.combat':     'Combat',
  'sheet.saves':      'Saving Throws',
  'sheet.skills':     'Skills',
  'sheet.attacks':    'Attacks',
  'sheet.notes':      'Notes',
  'sheet.summary':    'Level {level} {cls}',

  // ── Identity fields ──────────────────────────────────────────────
  'field.player':     'Player',
  'field.class':      'Class',
  'field.subclass':   'Subclass',
  'field.race':       'Species',
  'field.background': 'Background',
  'field.alignment':  'Alignment',
  'field.level':      'Level',

  // ── Combat fields ────────────────────────────────────────────────
  'field.maxHp':      'Max HP',
  'field.hp':         'Current HP',
  'field.tempHp':     'Temp HP',
  'field.ac':         'Armor Class',
  'field.initiative': 'Initiative',
  'field.speed':      'Speed',
  'field.profBonus':  'Proficiency Bonus',
  'field.notes':      'Notes (Markdown)',

  // ── Compact stat labels (read view) ──────────────────────────────
  'stat.hp':          'HP',
  'stat.ac':          'AC',
  'stat.init':        'Init',
  'stat.speed':       'Speed',
  'stat.pb':          'PB',
  'stat.passivePerc': 'Passive Perception',

  // ── Ability full names (abbreviations STR/DEX/… are universal) ────
  'ability.STR':      'Strength',
  'ability.DEX':      'Dexterity',
  'ability.CON':      'Constitution',
  'ability.INT':      'Intelligence',
  'ability.WIS':      'Wisdom',
  'ability.CHA':      'Charisma',

  // ── Skills ───────────────────────────────────────────────────────
  'skill.acrobatics':     'Acrobatics',
  'skill.animalHandling': 'Animal Handling',
  'skill.arcana':         'Arcana',
  'skill.athletics':      'Athletics',
  'skill.deception':      'Deception',
  'skill.history':        'History',
  'skill.insight':        'Insight',
  'skill.intimidation':   'Intimidation',
  'skill.investigation':  'Investigation',
  'skill.medicine':       'Medicine',
  'skill.nature':         'Nature',
  'skill.perception':     'Perception',
  'skill.performance':    'Performance',
  'skill.persuasion':     'Persuasion',
  'skill.religion':       'Religion',
  'skill.sleightOfHand':  'Sleight of Hand',
  'skill.stealth':        'Stealth',
  'skill.survival':       'Survival',

  // ── Spellbook ────────────────────────────────────────────────────
  'spellbook.empty':     'No spells yet. Add one with ＋ above.',
  'spellbook.add':       'Add spell',
  'spellbook.name':      'Spell name',
  'spellbook.level':     'Spell level (0 = cantrip)',
  'spellbook.school':    'School',
  'spellbook.prepared':  'Prepared',
  'spellbook.prepToggle': 'Toggle prepared',
  'spellbook.cantrip':   'Cantrip',
  'spellbook.lvlN':      'Level {n}',

  // ── Backpack / inventory ─────────────────────────────────────────
  'backpack.empty':      '—',
  'backpack.add':        'Add item',
  'backpack.name':       'Item name',
  'backpack.qty':        'Quantity',
  'backpack.cycleLoc':   'Move between Equipped / Ready / Pack',
  'backpack.currency':   'Currency',
  'backpack.addWeapon':  '＋ Weapon…',
  'backpack.addArmor':   '＋ Armor…',
  'backpack.attune':     'Toggle attunement (magic items)',
  'backpack.attuned':    'Attuned',
  'backpack.attunement': 'Attuned {n}/{limit}',
  'combat.mastery':      'Weapon mastery property',
  'combat.notProficient': 'Not proficient with this weapon',
  'loc.equipped':        'Equipped',
  'loc.ready':           'Ready',
  'loc.pack':            'Pack',
  'loc.equippedAbbr':    'Eq',
  'loc.readyAbbr':       'Rdy',
  'loc.packAbbr':        'Pk',
  'coin.pp':             'PP',
  'coin.gp':             'GP',
  'coin.ep':             'EP',
  'coin.sp':             'SP',
  'coin.cp':             'CP',

  // ── Engine-computed (shown when the rules engine addon is installed) ──
  'engine.auto':         'Values auto-calculated by the rules engine from your class, level, abilities and equipment.',
  'spell.saveDC':        'Save DC',
  'spell.attack':        'Spell Attack',
  'spell.prepared':      'Prepared {n}/{limit}',
  'spell.ritual':        'Ritual',
  'spell.slots':         'Slots',
  'spell.slotN':         'L{lvl}',
  'spell.cantripsN':     'Cantrips {n}/{known}',
  'spell.preparedN':     'Prepared {n}/{limit}',
  'spell.cantripPh':     '＋ Learn cantrip…',
  'spell.preparePh':     '＋ Prepare spell…',
  'spell.available':     'Available — drag into a slot (or click)',
  'spell.dragHint':      'Drag into a slot above, or click to add',
  'spell.emptySlot':     'drop here',
  'spell.alwaysPrepared': 'Always prepared (cannot be unprepared)',
  'spell.alwaysPreparedHdr': 'Always prepared',
  'spell.free':          'free 1/day',
  'spell.grantedBy':     'Granted by {src}',
  'spell.forcedDup':     'Already granted as always-prepared — duplicate.',
  'spell.extraSpells':   'Extra spells',
  'spell.addExtra':      'Add spell',
  'spell.copySpell':     'Copy into spellbook',
  'spell.copied':        'Copied from another spellbook',

  // ── Builder (rules-engine guided progression — appears when installed) ──
  'builder.soon':        'The guided Builder appears here when the rules engine and compendium addons are installed.',
  'builder.editHere':    'This character uses the rules engine. Edit it in the 🛠️ Builder tab — abilities, class & levels, and choices all live there, and the sheet auto-calculates.',
  'builder.totalLevel':  'Total Level',
  'builder.abilities':   'Ability Scores',
  'builder.baseHint':    'Enter base scores; the engine adds background / feat increases (capped at 20).',
  'builder.identity':    'Identity',
  'builder.lineage':     'Lineage',
  'builder.choose':      'Choose…',
  'builder.subclass':    'Subclass…',
  'builder.classes':     'Class & Levels',
  'builder.addClass':    'Add class (multiclass)',
  'builder.choices':     'Choices',
  'builder.skillProfs':  'Skill Proficiencies',
  'builder.expertise':   'Expertise',
  'builder.weaponMastery': 'Weapon Mastery',
  'builder.bgAsi':       '{bg}: ability score increase',
  'builder.originFeat':  'Origin feat: {feat}',
  'builder.contentPending': 'No options available yet (content pending).',
  'builder.asiOption':   'Ability Score Improvement',
  'builder.featOption':  'Feat',
  'builder.asiLevel':    '{cls} {lvl}: ASI or Feat',
  'builder.asiAbility':  'Ability +2…',
  'builder.progression': 'Progression',

  // ── Actions / misc ───────────────────────────────────────────────
  'action.hpMinus':   'Lose 1 HP',
  'action.hpPlus':    'Heal 1 HP',
  'action.remove':    'Remove',
  'misc.notSet':      '—',
  'misc.unnamed':     '(unnamed)',
  'misc.proficient':  'Proficient',
  'misc.expertise':   'Expertise',

  // ── Settings / help ──────────────────────────────────────────────
  'settings.label':   'Character Sheets',
  'help.title':       'D&D 5.5e Character Sheets',
  'help.body':        'Adds a fully hand-fillable D&D 5.5e character sheet to every character page, stored per character. Works standalone; when the rules engine and compendium addons are installed it can auto-fill stats from class/species/background choices. Characters in the database: {count}.',
};
