// English UI strings for dnd55e-sheets — the source of truth.
//
// Flat key → string catalog, mirroring the host's /i18n/en.json shape. English
// is always present and is the universal fallback; other locales layer on top
// (drop a strings/<locale>.js and registerCatalog it in entry.js — no other
// change). {placeholders} are interpolated by i18n.t(). Keep this file English
// only; translations never live here.

export default {
  // ── Tabs ─────────────────────────────────────────────────────────
  //  Overview = the host's native lore (we don't own it); the rest are the D&D
  //  sheet the addon adds. Builder is the rightmost, editors-only, engine mode.
  'tab.overview':     'Overview',
  'tab.stats':        'Character Sheet',
  'tab.combat':       'Combat',
  'tab.spellbook':    'Spellbook',
  'tab.backpack':     'Backpack',
  'tab.builder':      'Builder',
  'tab.overviewHint': 'Lore & background',
  'tab.statsHint':    'Abilities, saving throws & skills',
  'tab.combatHint':   'Attacks & resource trackers',
  'tab.spellbookHint':'Prepared spells & slots',
  'tab.backpackHint': 'Inventory & currency',
  'tab.builderHint':  'Class, levels & choices',

  // ── Section headers ──────────────────────────────────────────────
  'sheet.title':      'Character Sheet',
  'sheet.identity':   'Identity',
  'sheet.abilities':  'Ability Scores',
  'sheet.combat':     'Combat',
  'sheet.saves':      'Saving Throws',
  'sheet.skills':     'Skills',
  'sheet.attacks':    'Attacks',
  'sheet.notes':      'Notes',
  'sheet.summary':    'Level {level} {cls}',

  // ── Identity fields ──────────────────────────────────────────────
  'field.player':     'Player',
  'field.class':      'Class',
  'field.subclass':   'Subclass',
  'field.race':       'Species',
  'field.background': 'Background',
  'field.alignment':  'Alignment',
  'field.level':      'Level',

  // ── Combat fields ────────────────────────────────────────────────
  'field.maxHp':      'Max HP',
  'field.hp':         'Current HP',
  'field.tempHp':     'Temp HP',
  'field.ac':         'Armor Class',
  'field.initiative': 'Initiative',
  'field.speed':      'Speed',
  'field.profBonus':  'Proficiency Bonus',
  'field.notes':      'Notes (Markdown)',

  // ── Compact stat labels (read view) ──────────────────────────────
  'stat.hp':          'Hit Points',
  'stat.ac':          'AC',
  'stat.init':        'Initiative',
  'stat.speed':       'Speed',
  'stat.pb':          'Proficiency',
  'stat.passivePerc': 'Passive Perception',
  'stat.passivePercAbbr': 'Pass. Perc.',
  'stat.temp':        'Temp',

  // ── Header / sections ────────────────────────────────────────────
  'header.details':   'Details',
  'header.noClass':   'Unnamed adventurer',
  'sheet.savesShort': 'Saves',
  'sheet.notesEmpty': 'No notes yet.',
  'sheet.notesHint':  'Mechanical notes — resistances, conditions, reminders. Story & lore live in the page description (Edit).',
  'combat.title':     'Attacks',
  'combat.defenses':  'Defenses',
  'combat.noWeapons': 'No weapons readied. Add weapons in the Backpack and mark them Equipped or Ready to see attacks here.',
  'combat.weaponsHint': 'Equipped & readied weapons.',
  'combat.acSource':  'Armor Class',
  'combat.attunement': 'Attunement',

  // ── Resource trackers (Rage / Ki / slots / hit dice…) ────────────
  'tracker.title':    'Trackers',
  'tracker.add':      'Add tracker',
  'tracker.name':     'Rage, Ki, Slots…',
  'tracker.max':      'Max',
  'tracker.empty':    'No trackers yet.',
  'tracker.hint':     'Count limited resources — Rage, Ki, spell slots, hit dice. ± adjusts during play.',
  'tracker.minus':    'Spend one',
  'tracker.plus':     'Regain one',
  'tracker.reset':    'Reset to full',
  'tracker.rechShort': 'short rest',
  'tracker.rechLong':  'long rest',

  // ── Rest wizard ──────────────────────────────────────────────────
  'rest.button':      'Rest',
  'rest.title':       'Take a rest',
  'rest.hitDiceHint': 'Spend a Hit Die to heal by its average (+ CON). Prefer to roll? Spend it on the Hit Dice tracker and add your roll with HP ±.',
  'rest.noHitDice':   'No Hit Dice available.',
  'rest.noneLeft':    'none left',
  'rest.spendDie':    'Spend {die} · +{heal} HP',
  'rest.takeShort':   'Short rest',
  'rest.takeLong':    'Long rest',
  'rest.longSummary': 'Long rest → HP to full, regain {half} Hit Dice, and every resource resets by its rule.',
  'rest.amtFull':     'full',
  'rest.amtHalf':     'half',
  'rest.rechRule':    '{amt} on {on}',

  // ── Ability full names (abbreviations STR/DEX/… are universal) ────
  'ability.STR':      'Strength',
  'ability.DEX':      'Dexterity',
  'ability.CON':      'Constitution',
  'ability.INT':      'Intelligence',
  'ability.WIS':      'Wisdom',
  'ability.CHA':      'Charisma',

  // ── Skills ───────────────────────────────────────────────────────
  'skill.acrobatics':     'Acrobatics',
  'skill.animalHandling': 'Animal Handling',
  'skill.arcana':         'Arcana',
  'skill.athletics':      'Athletics',
  'skill.deception':      'Deception',
  'skill.history':        'History',
  'skill.insight':        'Insight',
  'skill.intimidation':   'Intimidation',
  'skill.investigation':  'Investigation',
  'skill.medicine':       'Medicine',
  'skill.nature':         'Nature',
  'skill.perception':     'Perception',
  'skill.performance':    'Performance',
  'skill.persuasion':     'Persuasion',
  'skill.religion':       'Religion',
  'skill.sleightOfHand':  'Sleight of Hand',
  'skill.stealth':        'Stealth',
  'skill.survival':       'Survival',

  // ── Spellbook ────────────────────────────────────────────────────
  'spellbook.empty':     'No spells yet. Add one with ＋ above.',
  'spellbook.add':       'Add spell',
  'spellbook.name':      'Spell name',
  'spellbook.level':     'Spell level (0 = cantrip)',
  'spellbook.school':    'School',
  'spellbook.prepared':  'Prepared',
  'spellbook.prepToggle': 'Toggle prepared',
  'spellbook.cantrip':   'Cantrip',
  'spellbook.lvlN':      'Level {n}',

  // ── Backpack / inventory ─────────────────────────────────────────
  'backpack.empty':      '—',
  'backpack.add':        'Add item',
  'backpack.name':       'Item name',
  'backpack.qty':        'Quantity',
  'backpack.cycleLoc':   'Move between Equipped / Ready / Pack',
  'backpack.currency':   'Currency',
  'backpack.addWeapon':  '＋ Weapon…',
  'backpack.addArmor':   '＋ Armor…',
  'backpack.attune':     'Toggle attunement (magic items)',
  'backpack.attunement': 'Attuned {n}/{limit}',
  'combat.mastery':      'Weapon mastery property',
  'combat.notProficient': 'Not proficient with this weapon',
  'loc.equipped':        'Equipped',
  'loc.ready':           'Ready',
  'loc.pack':            'Pack',
  'loc.equippedAbbr':    'Eq',
  'loc.readyAbbr':       'Rdy',
  'loc.packAbbr':        'Pk',
  'coin.pp':             'PP',
  'coin.gp':             'GP',
  'coin.ep':             'EP',
  'coin.sp':             'SP',
  'coin.cp':             'CP',

  // ── Engine-computed (shown when the rules engine addon is installed) ──
  'engine.auto':         'Values auto-calculated by the rules engine from your class, level, abilities and equipment.',
  'spell.saveDC':        'Save DC',
  'spell.attack':        'Spell Attack',
  'spell.prepared':      'Prepared {n}/{limit}',
  'spell.ritual':        'Ritual',
  'spell.slots':         'Slots',
  'spell.slotN':         'L{lvl}',
  'spell.cantripsN':     'Cantrips {n}/{known}',
  'spell.preparedN':     'Prepared {n}/{limit}',
  'spell.available':     'Available — drag into a slot (or click)',
  'spell.dragHint':      'Drag into a slot above, or click to add',
  'spell.emptySlot':     'drop here',
  'spell.alwaysPrepared': 'Always prepared (cannot be unprepared)',
  'spell.alwaysPreparedHdr': 'Always prepared',
  'spell.free':          'free 1/day',
  'spell.grantedBy':     'Granted by {src}',
  'spell.forcedDup':     'Already granted as always-prepared — duplicate.',
  'spell.extraSpells':   'Extra spells',
  'spell.addExtra':      'Add spell',
  'spell.copySpell':     'Copy into spellbook',
  'spell.copied':        'Copied from another spellbook',
  'spell.grantChoicesHdr': 'Granted spell choices',
  'spell.chooseGrant':   '{src}: choose {n} ({what})',

  // ── Builder (rules-engine guided progression — appears when installed) ──
  'builder.soon':        'The guided Builder appears here when the rules engine and compendium addons are installed.',
  'builder.editHere':    'This character uses the rules engine. On the sheet, press ✎ Edit to enter modification mode, then open the 🛠️ Builder tab — abilities, class & levels, and choices all live there, and the sheet auto-calculates.',
  'builder.totalLevel':  'Total Level',
  'builder.abilities':   'Ability Scores',
  'builder.baseHint':    'Enter base scores; the engine adds background / feat increases (capped at 20).',
  'builder.identity':    'Identity',
  'builder.lineage':     'Lineage',
  'builder.choose':      'Choose…',
  'builder.subclass':    'Subclass…',
  'builder.classes':     'Class & Levels',
  'builder.addClass':    'Add class (multiclass)',
  'builder.choices':     'Choices',
  'builder.skillProfs':  'Skill Proficiencies',
  'builder.expertise':   'Expertise',
  'builder.weaponMastery': 'Weapon Mastery',
  'builder.bgAsi':       '{bg}: ability score increase',
  'builder.originFeat':  'Origin feat: {feat}',
  'builder.contentPending': 'No options available yet (content pending).',
  'builder.asiOption':   'Ability Score Improvement',
  'builder.featOption':  'Feat',
  'builder.asiLevel':    '{cls} {lvl}: ASI or Feat',
  'builder.asiAbility':  'Ability +2…',
  'builder.progression': 'Progression',

  // ── Overrides (engine mode — a manual value that beats the computed one) ──
  'override.edit':    'Set a manual value (overrides the computed one)',
  'override.auto':    'Clear override — back to auto',
  'override.diverge': 'manual {manual} · auto {auto}',

  // ── Actions / misc ───────────────────────────────────────────────
  'action.hpMinus':   'Lose 1 HP',
  'action.hpPlus':    'Heal 1 HP',
  'action.remove':    'Remove',
  'action.cancel':    'Cancel',
  'misc.notSet':      '—',
  'misc.unnamed':     '(unnamed)',
  'misc.unknown':     '(unknown)',
  'misc.proficient':  'Proficient',
  'misc.notProficient': 'Not proficient',
  'misc.expertise':   'Expertise',

  // ── Settings / help ──────────────────────────────────────────────
  'settings.label':   'Character Sheets',
  'help.title':       'D&D 5.5e Character Sheets',
  'help.body':        'Adds a fully hand-fillable D&D 5.5e character sheet to every character page, stored per character. Works standalone; when the rules engine and compendium addons are installed it can auto-fill stats from class/species/background choices. Characters in the database: {count}.',
};
